services:
  - type: web
    name: dynergie-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python seed.py
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    plan: free
